service: aws-node-scheduled-cron-project
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

functions:
  getForSaleEventHandler:
    handler: index.getForSaleEventHandler
    timeout: 30
    events:
      - schedule: rate(1 minute)

  getTokenPurchasedEventHandler:
    handler: index.getTokenPurchasedEventHandler
    timeout: 30
    events:
      - schedule: rate(1 minute)

  getSaleCanceledEventHandler:
    handler: index.getSaleCanceledEventHandler
    timeout: 30
    events:
      - schedule: rate(1 minute)

  getPriceChangedEventHandler:
    handler: index.getPriceChangedEventHandler
    timeout: 30
    events:
      - schedule: rate(1 minute)

